import React from 'react';

type Props = {
  companyName?: string;
  contactEmail?: string;
  employees?: string;
  services?: string;
  message?: string;
};

export default function PricingRequestEmail({
  companyName = '',
  contactEmail = '',
  employees = '',
  services = '',
  message = '',
}: Props) {
  return (
    <html>
      <body style={{ fontFamily: 'Arial, sans-serif', color: '#111', lineHeight: 1.4 }}>
        <div style={{ maxWidth: 640, margin: '0 auto', padding: 20 }}>
          <h2 style={{ color: '#0f172a' }}>New Pricing Request</h2>

          <table cellPadding={8} cellSpacing={0} style={{ width: '100%', borderCollapse: 'collapse' }}>
            <tbody>
              <tr>
                <td style={{ fontWeight: 700, background: '#f8fafc', width: 180 }}>Company</td>
                <td>{companyName}</td>
              </tr>
              <tr>
                <td style={{ fontWeight: 700, background: '#f8fafc' }}>Contact Email</td>
                <td>{contactEmail}</td>
              </tr>
              <tr>
                <td style={{ fontWeight: 700, background: '#f8fafc' }}>Employees</td>
                <td>{employees}</td>
              </tr>
              <tr>
                <td style={{ fontWeight: 700, background: '#f8fafc' }}>Services</td>
                <td>{services}</td>
              </tr>
              <tr>
                <td style={{ fontWeight: 700, background: '#f8fafc' }}>Message</td>
                <td style={{ whiteSpace: 'pre-wrap' }}>{message}</td>
              </tr>
            </tbody>
          </table>

          <p style={{ marginTop: 20, color: '#475569' }}>
            This message was generated by your Secure-Sense website. Reply to the contact email to follow up.
          </p>
        </div>
      </body>
    </html>
  );
}
